### ISSUE TITLE
can't find variable self

### ISSUE THREAD

**Issue by ntk860** [pritishvaidya/react-native-soundcloud-waveform#1]
I am getting this error 'cant find variable self'
can you update your react-native version please ?

**Comment by pritishvaidya** [comment]
I'll have a look at it and update peer dependencies to support all `react` and `react-native` versions, it is probably a `whatwg-fetch` version issue

**Comment by pritishvaidya** [comment]
I have published a new version with the [fix](https://www.npmjs.com/package/react-native-soundcloud-waveform) and updated the [example](https://github.com/pritishvaidya/react-native-soundcloud-waveform/tree/master/example). Let me know if it solves the issue.

**Comment by vbnospace** [comment]
its working now, thank you!
