### ISSUE TITLE
URL from other sources

### ISSUE THREAD

**Issue by vbnospace** [pritishvaidya/react-native-soundcloud-waveform#2]
Is it possible for you make it work with url from other sources ?

**Comment by pritishvaidya** [comment]
I haven't investigated other waveform url's but this whole idea is build on getting the normalized values of the song from the waveform. Example - https://w1.sndcdn.com/PP3Eb34ToNki_m.png when replaced with https://w1.sndcdn.com/PP3Eb34ToNki_m.json gives the samples of the waveform. 

If there are any other platforms that support similar feature, i'll be happy to add them or make another project.
